### ISSUE TITLE
A small question about the pipeline and the architecture of model 

### ISSUE THREAD

**Issue by CHMimilanlan** [lyk412/Consistent123#1]
Since I'm new in this domain, after reading your paper carefully, I am more concerned about whether the output of stage 1 in the model pipeline is nerf, which seem not to be explained in detail.
My guess is that NeRF was used in the middle process of stage 1 and stage 2, and in the final output, the DMTet model was used to convert the NeRF data into mesh.
Is my guess correct? I will be greatfull for your timely response.

 
![image](https://github.com/user-attachments/assets/889c9b32-2fc3-48f3-994a-f3463f58b6a6)

**Comment by lyk412** [comment]
@CHMimilanlan Yes, your guess is correct.  The output of stage 1 is nerf, and we still use nerf after detecting the optimization boundary, but at a later stage we switch to  DMTet as an output.
